In [1]:
import numpy as np
import pandas as pd
from dyres.dyres import DyRes

In [2]:
import dyres

In [3]:
dyres.__version__

'0.2.1.dev7+g18caa87.d20250516'

In [6]:
file = "TestGasFlow1DFV_A.mat"

In [7]:
dy = DyRes(file)

In [8]:
dy.names

['Time',
 'system.allowFlowReversal',
 'system.initOpt',
 'system.p_amb',
 'system.T_amb',
 'system.T_wb',
 'system.fnom',
 'Nnodes',
 'Lhex',
 'Dihex',
 'rhex',
 'omegahex',
 'Ahex',
 'Cfhex',
 'whex',
 'phex',
 'Tinhex',
 'Touthex',
 'W',
 'gamma',
 'dMtot_dp',
 'dw_dp',
 'tau',
 'Mhex',
 'Mbal',
 'der(Mbal)',
 'Merr',
 'Source.gas.p',
 'Source.gas.h',
 'Source.gas.d',
 'Source.gas.T',
 'Source.gas.X[1]',
 'Source.gas.u',
 'Source.gas.R',
 'Source.gas.MM',
 'Source.gas.state.p',
 'Source.gas.state.T',
 'Source.gas.preferredMediumStates',
 'Source.gas.standardOrderComponents',
 'Source.gas.T_degC',
 'Source.gas.p_bar',
 'Source.p0',
 'Source.T',
 'Source.Xnom[1]',
 'Source.w0',
 'Source.G',
 'Source.allowFlowReversal',
 'Source.use_in_w0',
 'Source.use_in_T',
 'Source.use_in_X',
 'Source.w',
 'Source.flange.m_flow',
 'Source.flange.p',
 'Source.flange.h_outflow',
 'Source.in_T',
 'Sink.gas.p',
 'Sink.gas.h',
 'Sink.gas.d',
 'Sink.gas.T',
 'Sink.gas.X[1]',
 'Sink.gas.u',
 'Sink.gas.R',

In [9]:
dy['EventCounter']

array([2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 3., 3., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 3., 3., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 4., 4., 4., 4.

In [6]:
## accessing at one point in time

dy['EventCounter', 70]

5.0

In [7]:
## accessing at range of time

dy['EventCounter', 70, 80]

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.,
       5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.,
       5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.,
       5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.], dtype=float32)

In [8]:
## skipping every third idx

dy['EventCounter', 70, 80, 3]

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.,
       5., 5., 5., 5.], dtype=float32)

In [9]:
## corresponding time

dy['Time', 70, 80, 3]

array([70.08, 70.56, 71.04, 71.52, 72.  , 72.48, 72.96, 73.44, 73.92,
       74.4 , 74.88, 75.36, 75.84, 76.32, 76.8 , 77.28, 77.76, 78.24,
       78.72, 79.2 , 79.68], dtype=float32)

In [12]:
dy['Time', 70]

70.0

In [19]:
sli = dy._timeSlice((70,80,3))
dy.Time[sli] # this way is made to be ugly by design

array([70.08, 70.56, 71.04, 71.52, 72.  , 72.48, 72.96, 73.44, 73.92,
       74.4 , 74.88, 75.36, 75.84, 76.32, 76.8 , 77.28, 77.76, 78.24,
       78.72, 79.2 , 79.68], dtype=float32)

In [20]:
dy['hex.N']

10.0

In [12]:
dy['hex.wall.T[3]', 50, 60]

array([313.2222 , 313.22168, 313.22116, 313.22067, 313.2202 , 313.21976,
       313.2193 , 313.21887, 313.21844, 313.21805, 313.21765, 313.21725,
       313.2169 , 313.21655, 313.2162 , 313.21588, 313.21555, 313.21524,
       313.21494, 313.21463, 313.21436, 313.21408, 313.2138 , 313.21353,
       313.2133 , 313.21304, 313.2128 , 313.2126 , 313.21234, 313.21213,
       313.21194, 313.21173, 313.21155, 313.21133, 313.21115, 313.211  ,
       313.21082, 313.21063, 313.21048, 313.21033, 313.21017, 313.21002,
       313.2099 , 313.20975, 313.20963, 313.20947, 313.20935, 313.20923,
       313.2091 , 313.209  , 313.2089 , 313.20877, 313.20868, 313.2086 ,
       313.2085 , 313.20837, 313.20828, 313.20822, 313.20813, 313.20804,
       313.20795, 313.2079 ], dtype=float32)

In [26]:
dy['Time']

array([ 0.  ,  0.16,  0.32,  0.48,  0.64,  0.8 ,  0.96,  1.12,  1.28,
        1.44,  1.6 ,  1.76,  1.92,  2.08,  2.24,  2.4 ,  2.56,  2.72,
        2.88,  3.04,  3.2 ,  3.36,  3.52,  3.68,  3.84,  4.  ,  4.16,
        4.32,  4.48,  4.64,  4.8 ,  4.96,  5.12,  5.28,  5.44,  5.6 ,
        5.76,  5.92,  6.08,  6.24,  6.4 ,  6.56,  6.72,  6.88,  7.04,
        7.2 ,  7.36,  7.52,  7.68,  7.84,  8.  ,  8.16,  8.32,  8.48,
        8.64,  8.8 ,  8.96,  9.12,  9.28,  9.44,  9.6 ,  9.76,  9.92,
       10.  , 10.  , 10.08, 10.24, 10.4 , 10.56, 10.72, 10.88, 11.04,
       11.2 , 11.36, 11.52, 11.68, 11.84, 12.  , 12.16, 12.32, 12.48,
       12.64, 12.8 , 12.96, 13.12, 13.28, 13.44, 13.6 , 13.76, 13.92,
       14.08, 14.24, 14.4 , 14.56, 14.72, 14.88, 15.04, 15.2 , 15.36,
       15.52, 15.68, 15.84, 16.  , 16.16, 16.32, 16.48, 16.64, 16.8 ,
       16.96, 17.12, 17.28, 17.44, 17.6 , 17.76, 17.92, 18.08, 18.24,
       18.4 , 18.56, 18.72, 18.88, 19.04, 19.2 , 19.36, 19.52, 19.68,
       19.84, 20.  ,

In [32]:
dy.to_json('t.json')

In [8]:
dy2 = DyRes('TestGasFlow1DFV_A.json')

In [9]:
dy2['EventCounter']

array([2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 3., 3., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 3., 3., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 4., 4., 4., 4.

In [35]:
dy2._DyRes__mat['dataInfo'].shape

(2, 576)

In [36]:
dy.to_mat('t.mat')

In [37]:
dy3 = DyRes('t.mat')

In [38]:
dy3['EventCounter']

array([2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 3., 3., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 3., 3., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 4., 4., 4., 4.

In [39]:
dy3['hex.wall.T[2]']

array([300.        , 300.        , 300.        , 300.        ,
       300.        , 300.        , 300.        , 300.        ,
       300.        , 300.        , 300.        , 300.        ,
       300.        , 300.        , 300.        , 300.        ,
       300.        , 300.        , 300.        , 300.        ,
       300.        , 300.        , 300.        , 300.        ,
       300.        , 300.        , 300.        , 300.        ,
       300.        , 300.        , 300.        , 300.        ,
       300.        , 300.        , 300.        , 300.        ,
       300.        , 300.        , 300.        , 300.        ,
       300.        , 300.        , 300.        , 300.        ,
       300.        , 300.        , 300.        , 300.        ,
       300.        , 300.        , 300.        , 300.        ,
       300.        , 300.        , 300.        , 300.        ,
       300.        , 300.        , 300.        , 300.        ,
       300.        , 300.        , 300.        , 300.  

In [40]:
dy3['hex.N']

10.0

In [42]:
dy.to_hdf5('t.h5')


In [43]:
dy4 = DyRes('t.h5')

In [44]:
dy4['EventCounter']

array([2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 3., 3., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 3., 3., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 4., 4., 4., 4.

In [45]:
dy4.names

['Time',
 'system.allowFlowReversal',
 'system.initOpt',
 'system.p_amb',
 'system.T_amb',
 'system.T_wb',
 'system.fnom',
 'Nnodes',
 'Lhex',
 'Dihex',
 'rhex',
 'omegahex',
 'Ahex',
 'Cfhex',
 'whex',
 'phex',
 'Tinhex',
 'Touthex',
 'W',
 'gamma',
 'dMtot_dp',
 'dw_dp',
 'tau',
 'Mhex',
 'Mbal',
 'der(Mbal)',
 'Merr',
 'Source.gas.p',
 'Source.gas.h',
 'Source.gas.d',
 'Source.gas.T',
 'Source.gas.X[1]',
 'Source.gas.u',
 'Source.gas.R',
 'Source.gas.MM',
 'Source.gas.state.p',
 'Source.gas.state.T',
 'Source.gas.preferredMediumStates',
 'Source.gas.standardOrderComponents',
 'Source.gas.T_degC',
 'Source.gas.p_bar',
 'Source.p0',
 'Source.T',
 'Source.Xnom[1]',
 'Source.w0',
 'Source.G',
 'Source.allowFlowReversal',
 'Source.use_in_w0',
 'Source.use_in_T',
 'Source.use_in_X',
 'Source.w',
 'Source.flange.m_flow',
 'Source.flange.p',
 'Source.flange.h_outflow',
 'Source.in_T',
 'Sink.gas.p',
 'Sink.gas.h',
 'Sink.gas.d',
 'Sink.gas.T',
 'Sink.gas.X[1]',
 'Sink.gas.u',
 'Sink.gas.R',

In [46]:
dy4['hex.wall.T[2]']

array([300.        , 300.        , 300.        , 300.        ,
       300.        , 300.        , 300.        , 300.        ,
       300.        , 300.        , 300.        , 300.        ,
       300.        , 300.        , 300.        , 300.        ,
       300.        , 300.        , 300.        , 300.        ,
       300.        , 300.        , 300.        , 300.        ,
       300.        , 300.        , 300.        , 300.        ,
       300.        , 300.        , 300.        , 300.        ,
       300.        , 300.        , 300.        , 300.        ,
       300.        , 300.        , 300.        , 300.        ,
       300.        , 300.        , 300.        , 300.        ,
       300.        , 300.        , 300.        , 300.        ,
       300.        , 300.        , 300.        , 300.        ,
       300.        , 300.        , 300.        , 300.        ,
       300.        , 300.        , 300.        , 300.        ,
       300.        , 300.        , 300.        , 300.  

In [47]:
dy5 = DyRes("FaisalPaper0.mat")

In [48]:
dy5.names

['Time',
 'system.allowFlowReversal',
 'system.initOpt',
 'system.p_amb',
 'system.T_amb',
 'system.T_wb',
 'system.fnom',
 'sourceMassFlow.gas.p',
 'sourceMassFlow.gas.Xi[1]',
 'sourceMassFlow.gas.Xi[2]',
 'sourceMassFlow.gas.Xi[3]',
 'sourceMassFlow.gas.Xi[4]',
 'sourceMassFlow.gas.Xi[5]',
 'sourceMassFlow.gas.Xi[6]',
 'sourceMassFlow.gas.h',
 'sourceMassFlow.gas.d',
 'sourceMassFlow.gas.T',
 'sourceMassFlow.gas.X[1]',
 'sourceMassFlow.gas.X[2]',
 'sourceMassFlow.gas.X[3]',
 'sourceMassFlow.gas.X[4]',
 'sourceMassFlow.gas.X[5]',
 'sourceMassFlow.gas.X[6]',
 'sourceMassFlow.gas.u',
 'sourceMassFlow.gas.R',
 'sourceMassFlow.gas.MM',
 'sourceMassFlow.gas.state.p',
 'sourceMassFlow.gas.state.T',
 'sourceMassFlow.gas.state.X[1]',
 'sourceMassFlow.gas.state.X[2]',
 'sourceMassFlow.gas.state.X[3]',
 'sourceMassFlow.gas.state.X[4]',
 'sourceMassFlow.gas.state.X[5]',
 'sourceMassFlow.gas.state.X[6]',
 'sourceMassFlow.gas.preferredMediumStates',
 'sourceMassFlow.gas.standardOrderComponents',
 

In [49]:
dy5['stack.UnitCell[1, 2].PEN.rho']

5900.0

In [50]:
dy5['stack.UnitCell[1, 2].PEN.Tpen']

array([1073.15  , 1073.15  , 1073.15  , 1073.15  , 1073.15  , 1073.15  ,
       1073.15  , 1073.15  , 1073.15  , 1073.15  , 1073.15  , 1073.15  ,
       1073.1499, 1073.1499, 1073.1499, 1073.1499, 1073.1498, 1073.1498,
       1073.1498, 1073.1497, 1073.1497, 1073.1497, 1073.1495, 1073.1495,
       1073.1495, 1073.1494, 1073.1494, 1073.1493, 1073.1492, 1073.1492,
       1073.149 , 1073.1489, 1073.1488, 1073.1487, 1073.1486, 1073.1483,
       1073.1481, 1073.1477, 1073.1475, 1073.1472, 1073.1471, 1073.1469,
       1073.1464, 1073.146 , 1073.1456, 1073.1454, 1073.1447, 1073.144 ,
       1073.1437, 1073.143 , 1073.1427, 1073.144 , 1073.149 , 1073.1625,
       1073.191 , 1073.2208, 1073.2666, 1073.3344, 1073.3971, 1073.5322,
       1073.6366, 1073.7178, 1073.8059, 1073.9025, 1073.9025, 1073.9026,
       1073.9031, 1073.9083, 1073.9324, 1073.9324, 1073.9326, 1073.9479,
       1074.0261, 1074.0735, 1074.1185, 1074.1215, 1074.0421, 1073.923 ,
       1073.8137, 1073.6124, 1073.4468, 1073.2374, 

In [51]:
dy5.to_mat("FaisalPaper0_dyres.mat")

In [52]:
dy6 = DyRes("FaisalPaper0_dyres.mat")

In [53]:
dy6.names

['Time',
 'system.allowFlowReversal',
 'system.initOpt',
 'system.p_amb',
 'system.T_amb',
 'system.T_wb',
 'system.fnom',
 'sourceMassFlow.gas.p',
 'sourceMassFlow.gas.Xi[1]',
 'sourceMassFlow.gas.Xi[2]',
 'sourceMassFlow.gas.Xi[3]',
 'sourceMassFlow.gas.Xi[4]',
 'sourceMassFlow.gas.Xi[5]',
 'sourceMassFlow.gas.Xi[6]',
 'sourceMassFlow.gas.h',
 'sourceMassFlow.gas.d',
 'sourceMassFlow.gas.T',
 'sourceMassFlow.gas.X[1]',
 'sourceMassFlow.gas.X[2]',
 'sourceMassFlow.gas.X[3]',
 'sourceMassFlow.gas.X[4]',
 'sourceMassFlow.gas.X[5]',
 'sourceMassFlow.gas.X[6]',
 'sourceMassFlow.gas.u',
 'sourceMassFlow.gas.R',
 'sourceMassFlow.gas.MM',
 'sourceMassFlow.gas.state.p',
 'sourceMassFlow.gas.state.T',
 'sourceMassFlow.gas.state.X[1]',
 'sourceMassFlow.gas.state.X[2]',
 'sourceMassFlow.gas.state.X[3]',
 'sourceMassFlow.gas.state.X[4]',
 'sourceMassFlow.gas.state.X[5]',
 'sourceMassFlow.gas.state.X[6]',
 'sourceMassFlow.gas.preferredMediumStates',
 'sourceMassFlow.gas.standardOrderComponents',
 

In [54]:
dy6['stack.UnitCell[1, 2].PEN.rho']

5900.0

In [55]:
dy6['stack.UnitCell[1, 2].PEN.Tpen']

array([1073.15002441, 1073.15002441, 1073.15002441, 1073.15002441,
       1073.15002441, 1073.15002441, 1073.15002441, 1073.15002441,
       1073.15002441, 1073.15002441, 1073.15002441, 1073.15002441,
       1073.14990234, 1073.14990234, 1073.14990234, 1073.14990234,
       1073.14978027, 1073.14978027, 1073.14978027, 1073.1496582 ,
       1073.1496582 , 1073.1496582 , 1073.14953613, 1073.14953613,
       1073.14953613, 1073.14941406, 1073.14941406, 1073.14929199,
       1073.14916992, 1073.14916992, 1073.14904785, 1073.14892578,
       1073.14880371, 1073.14868164, 1073.14855957, 1073.14831543,
       1073.14807129, 1073.14770508, 1073.14746094, 1073.1472168 ,
       1073.14709473, 1073.14685059, 1073.1463623 , 1073.14599609,
       1073.14562988, 1073.14538574, 1073.14465332, 1073.14404297,
       1073.14367676, 1073.14294434, 1073.1427002 , 1073.14404297,
       1073.14904785, 1073.16247559, 1073.19104004, 1073.2208252 ,
       1073.26660156, 1073.33435059, 1073.39709473, 1073.53222

In [56]:
dy5.to_hdf5('FaisalPaper0.h5')